// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#include <odb/pre.hxx>

// Begin prologue.
//
//
// End prologue.

#include "mcsf_dicomdatabase_printfilmtable-odb.hxx"

#include <cstring> // std::memcpy

#include <odb/cache-traits.hxx>
#include <odb/schema-catalog-impl.hxx>
#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

#include <odb/mysql/traits.hxx>
#include <odb/mysql/database.hxx>
#include <odb/mysql/transaction.hxx>
#include <odb/mysql/connection.hxx>
#include <odb/mysql/statement.hxx>
#include <odb/mysql/statement-cache.hxx>
#include <odb/mysql/object-statements.hxx>
#include <odb/mysql/container-statements.hxx>
#include <odb/mysql/exceptions.hxx>
#include <odb/mysql/result.hxx>
#include <odb/mysql/enum.hxx>

namespace odb
{
  // PrintFilmTable
  //

  const mysql::query_column<
    mysql::value_traits< int, mysql::id_long >::query_type,
    mysql::id_long >
  access::object_traits< ::PrintFilmTable >::query_columns::JobID (
    "_.`JobID`");

  const mysql::query_column<
    mysql::value_traits< int, mysql::id_long >::query_type,
    mysql::id_long >
  access::object_traits< ::PrintFilmTable >::query_columns::FilmID (
    "_.`FilmID`");

  const mysql::query_column<
    mysql::value_traits< int, mysql::id_long >::query_type,
    mysql::id_long >
  access::object_traits< ::PrintFilmTable >::query_columns::FilmAmount (
    "_.`FilmAmount`");

  const mysql::query_column<
    mysql::value_traits< ::std::string, mysql::id_string >::query_type,
    mysql::id_string >
  access::object_traits< ::PrintFilmTable >::query_columns::Layout (
    "_.`Layout`");

  const mysql::query_column<
    mysql::value_traits< ::std::string, mysql::id_string >::query_type,
    mysql::id_string >
  access::object_traits< ::PrintFilmTable >::query_columns::FilmSize (
    "_.`FilmSize`");

  const mysql::query_column<
    mysql::value_traits< ::PrintFilmTable::DATE_BOOST, mysql::id_date >::query_type,
    mysql::id_date >
  access::object_traits< ::PrintFilmTable >::query_columns::CreateDate (
    "_.`CreateDate`");

  const mysql::query_column<
    mysql::value_traits< ::PrintFilmTable::TIME_BOOST, mysql::id_time >::query_type,
    mysql::id_time >
  access::object_traits< ::PrintFilmTable >::query_columns::CreateTime (
    "_.`CreateTime`");

  const mysql::query_column<
    mysql::value_traits< int, mysql::id_long >::query_type,
    mysql::id_long >
  access::object_traits< ::PrintFilmTable >::query_columns::HavePrinted (
    "_.`HavePrinted`");

  access::object_traits< ::PrintFilmTable >::id_type
  access::object_traits< ::PrintFilmTable >::
  id (const image_type& i)
  {
    id_type id;
    mysql::value_traits<
        int,
        mysql::id_long >::set_value (
      id, i.m_JobID_value, i.m_JobID_null);

    return id;
  }

  bool access::object_traits< ::PrintFilmTable >::
  grow (image_type& i, my_bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // m_JobID
    //
    t[0UL] = 0;

    // m_FilmID
    //
    t[1UL] = 0;

    // m_FilmAmount
    //
    t[2UL] = 0;

    // m_Layout
    //
    if (t[3UL])
    {
      i.m_Layout_value.capacity (i.m_Layout_size);
      grew = true;
    }

    // m_FilmSize
    //
    if (t[4UL])
    {
      i.m_FilmSize_value.capacity (i.m_FilmSize_size);
      grew = true;
    }

    // m_CreateDate
    //
    t[5UL] = 0;

    // m_CreateTime
    //
    t[6UL] = 0;

    // m_HavePrinted
    //
    t[7UL] = 0;

    return grew;
  }

  void access::object_traits< ::PrintFilmTable >::
  bind (MYSQL_BIND* b, image_type& i, bool out)
  {
    ODB_POTENTIALLY_UNUSED (out);

    std::size_t n (0);

    // m_JobID
    //
    b[n].buffer_type = MYSQL_TYPE_LONG;
    b[n].is_unsigned = 0;
    b[n].buffer = &i.m_JobID_value;
    b[n].is_null = &i.m_JobID_null;
    n++;

    // m_FilmID
    //
    b[n].buffer_type = MYSQL_TYPE_LONG;
    b[n].is_unsigned = 0;
    b[n].buffer = &i.m_FilmID_value;
    b[n].is_null = &i.m_FilmID_null;
    n++;

    // m_FilmAmount
    //
    b[n].buffer_type = MYSQL_TYPE_LONG;
    b[n].is_unsigned = 0;
    b[n].buffer = &i.m_FilmAmount_value;
    b[n].is_null = &i.m_FilmAmount_null;
    n++;

    // m_Layout
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i.m_Layout_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i.m_Layout_value.capacity ());
    b[n].length = &i.m_Layout_size;
    b[n].is_null = &i.m_Layout_null;
    n++;

    // m_FilmSize
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i.m_FilmSize_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i.m_FilmSize_value.capacity ());
    b[n].length = &i.m_FilmSize_size;
    b[n].is_null = &i.m_FilmSize_null;
    n++;

    // m_CreateDate
    //
    b[n].buffer_type = MYSQL_TYPE_DATE;
    b[n].buffer = &i.m_CreateDate_value;
    b[n].is_null = &i.m_CreateDate_null;
    n++;

    // m_CreateTime
    //
    b[n].buffer_type = MYSQL_TYPE_TIME;
    b[n].buffer = &i.m_CreateTime_value;
    b[n].is_null = &i.m_CreateTime_null;
    n++;

    // m_HavePrinted
    //
    b[n].buffer_type = MYSQL_TYPE_LONG;
    b[n].is_unsigned = 0;
    b[n].buffer = &i.m_HavePrinted_value;
    b[n].is_null = &i.m_HavePrinted_null;
    n++;
  }

  void access::object_traits< ::PrintFilmTable >::
  bind (MYSQL_BIND* b, id_image_type& i)
  {
    std::size_t n (0);
    b[n].buffer_type = MYSQL_TYPE_LONG;
    b[n].is_unsigned = 0;
    b[n].buffer = &i.id_value;
    b[n].is_null = &i.id_null;
  }

  bool access::object_traits< ::PrintFilmTable >::
  init (image_type& i, const object_type& o)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);

    bool grew (false);

    // m_JobID
    //
    {
      bool is_null;
      mysql::value_traits<
          int,
          mysql::id_long >::set_image (
        i.m_JobID_value, is_null, o.m_JobID);
      i.m_JobID_null = is_null;
    }

    // m_FilmID
    //
    {
      bool is_null;
      mysql::value_traits<
          int,
          mysql::id_long >::set_image (
        i.m_FilmID_value, is_null, o.m_FilmID);
      i.m_FilmID_null = is_null;
    }

    // m_FilmAmount
    //
    {
      bool is_null;
      mysql::value_traits<
          int,
          mysql::id_long >::set_image (
        i.m_FilmAmount_value, is_null, o.m_FilmAmount);
      i.m_FilmAmount_null = is_null;
    }

    // m_Layout
    //
    {
      bool is_null;
      std::size_t size (0);
      std::size_t cap (i.m_Layout_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i.m_Layout_value,
        size,
        is_null,
        o.m_Layout);
      i.m_Layout_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i.m_Layout_value.capacity ());
      i.m_Layout_null = is_null;
    }

    // m_FilmSize
    //
    {
      bool is_null;
      std::size_t size (0);
      std::size_t cap (i.m_FilmSize_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i.m_FilmSize_value,
        size,
        is_null,
        o.m_FilmSize);
      i.m_FilmSize_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i.m_FilmSize_value.capacity ());
      i.m_FilmSize_null = is_null;
    }

    // m_CreateDate
    //
    {
      bool is_null;
      mysql::value_traits<
          ::PrintFilmTable::DATE_BOOST,
          mysql::id_date >::set_image (
        i.m_CreateDate_value, is_null, o.m_CreateDate);
      i.m_CreateDate_null = is_null;
    }

    // m_CreateTime
    //
    {
      bool is_null;
      mysql::value_traits<
          ::PrintFilmTable::TIME_BOOST,
          mysql::id_time >::set_image (
        i.m_CreateTime_value, is_null, o.m_CreateTime);
      i.m_CreateTime_null = is_null;
    }

    // m_HavePrinted
    //
    {
      bool is_null;
      mysql::value_traits<
          int,
          mysql::id_long >::set_image (
        i.m_HavePrinted_value, is_null, o.m_HavePrinted);
      i.m_HavePrinted_null = is_null;
    }

    return grew;
  }

  void access::object_traits< ::PrintFilmTable >::
  init (object_type& o, const image_type& i, database& db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // m_JobID
    //
    mysql::value_traits<
        int,
        mysql::id_long >::set_value (
      o.m_JobID, i.m_JobID_value, i.m_JobID_null);

    // m_FilmID
    //
    mysql::value_traits<
        int,
        mysql::id_long >::set_value (
      o.m_FilmID, i.m_FilmID_value, i.m_FilmID_null);

    // m_FilmAmount
    //
    mysql::value_traits<
        int,
        mysql::id_long >::set_value (
      o.m_FilmAmount, i.m_FilmAmount_value, i.m_FilmAmount_null);

    // m_Layout
    //
    mysql::value_traits<
        ::std::string,
        mysql::id_string >::set_value (
      o.m_Layout,
      i.m_Layout_value,
      i.m_Layout_size,
      i.m_Layout_null);

    // m_FilmSize
    //
    mysql::value_traits<
        ::std::string,
        mysql::id_string >::set_value (
      o.m_FilmSize,
      i.m_FilmSize_value,
      i.m_FilmSize_size,
      i.m_FilmSize_null);

    // m_CreateDate
    //
    mysql::value_traits<
        ::PrintFilmTable::DATE_BOOST,
        mysql::id_date >::set_value (
      o.m_CreateDate, i.m_CreateDate_value, i.m_CreateDate_null);

    // m_CreateTime
    //
    mysql::value_traits<
        ::PrintFilmTable::TIME_BOOST,
        mysql::id_time >::set_value (
      o.m_CreateTime, i.m_CreateTime_value, i.m_CreateTime_null);

    // m_HavePrinted
    //
    mysql::value_traits<
        int,
        mysql::id_long >::set_value (
      o.m_HavePrinted, i.m_HavePrinted_value, i.m_HavePrinted_null);
  }

  void access::object_traits< ::PrintFilmTable >::
  init (id_image_type& i, const id_type& id)
  {
    {
      bool is_null;
      mysql::value_traits<
          int,
          mysql::id_long >::set_image (
        i.id_value, is_null, id);
      i.id_null = is_null;
    }
  }

  struct access::object_traits< ::PrintFilmTable >::container_statement_cache_type
  {
    container_statement_cache_type (mysql::connection&)
    {
    }
  };

  const char* const access::object_traits< ::PrintFilmTable >::persist_statement =
  "INSERT INTO `PrintFilmTable` ("
  "`JobID`,"
  "`FilmID`,"
  "`FilmAmount`,"
  "`Layout`,"
  "`FilmSize`,"
  "`CreateDate`,"
  "`CreateTime`,"
  "`HavePrinted`"
  ") VALUES (?,?,?,?,?,?,?,?)";

  const char* const access::object_traits< ::PrintFilmTable >::find_statement =
  "SELECT "
  "_.`JobID`,"
  "_.`FilmID`,"
  "_.`FilmAmount`,"
  "_.`Layout`,"
  "_.`FilmSize`,"
  "_.`CreateDate`,"
  "_.`CreateTime`,"
  "_.`HavePrinted`"
  " FROM `PrintFilmTable` AS _"
  " WHERE _.`JobID` = ?";

  const char* const access::object_traits< ::PrintFilmTable >::update_statement =
  "UPDATE `PrintFilmTable` SET "
  "`JobID` = ?,"
  "`FilmID` = ?,"
  "`FilmAmount` = ?,"
  "`Layout` = ?,"
  "`FilmSize` = ?,"
  "`CreateDate` = ?,"
  "`CreateTime` = ?,"
  "`HavePrinted` = ?"
  " WHERE `JobID` = ?";

  const char* const access::object_traits< ::PrintFilmTable >::erase_statement =
  "DELETE FROM `PrintFilmTable`"
  " WHERE `JobID` = ?";

  const char* const access::object_traits< ::PrintFilmTable >::query_clause =
  "SELECT "
  "_.`JobID`,"
  "_.`FilmID`,"
  "_.`FilmAmount`,"
  "_.`Layout`,"
  "_.`FilmSize`,"
  "_.`CreateDate`,"
  "_.`CreateTime`,"
  "_.`HavePrinted`"
  " FROM `PrintFilmTable` AS _"
  " ";

  void access::object_traits< ::PrintFilmTable >::
  persist (database&, const object_type& obj)
  {
    using namespace mysql;

    connection& conn (mysql::transaction::current ().connection ());
    object_statements< object_type >& sts (
      conn.statement_cache ().find<object_type> ());
    image_type& im (sts.image ());
    binding& imb (sts.in_image_binding ());

    if (init (im, obj))
      im.version++;

    if (im.version != sts.in_image_version () || imb.version == 0)
    {
      bind (imb.bind, im, false);
      sts.in_image_version (im.version);
      imb.version++;
    }

    insert_statement& st (sts.persist_statement ());
    if (!st.execute ())
      throw object_already_persistent ();
  }

  void access::object_traits< ::PrintFilmTable >::
  update (database&, const object_type& obj)
  {
    using namespace mysql;

    connection& conn (mysql::transaction::current ().connection ());
    object_statements< object_type >& sts (
      conn.statement_cache ().find<object_type> ());

    id_image_type& i (sts.id_image ());
    init (i, obj.m_JobID);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    image_type& im (sts.image ());
    binding& imb (sts.in_image_binding ());

    if (init (im, obj))
      im.version++;

    if (im.version != sts.in_image_version () || imb.version == 0)
    {
      bind (imb.bind, im, false);
      sts.in_image_version (im.version);
      imb.version++;
    }

    sts.update_statement ().execute ();
  }

  void access::object_traits< ::PrintFilmTable >::
  erase (database&, const id_type& id)
  {
    using namespace mysql;

    connection& conn (mysql::transaction::current ().connection ());
    object_statements< object_type >& sts (
      conn.statement_cache ().find<object_type> ());

    id_image_type& i (sts.id_image ());
    init (i, id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    if (sts.erase_statement ().execute () != 1)
      throw object_not_persistent ();
  }

  access::object_traits< ::PrintFilmTable >::pointer_type
  access::object_traits< ::PrintFilmTable >::
  find (database& db, const id_type& id)
  {
    using namespace mysql;

    connection& conn (mysql::transaction::current ().connection ());
    object_statements< object_type >& sts (
      conn.statement_cache ().find<object_type> ());
    object_statements< object_type >::auto_lock l (sts);

    if (l.locked ())
    {
      if (!find_ (sts, id))
        return pointer_type ();
    }

    pointer_type p (
      access::object_factory< object_type, pointer_type  >::create ());
    pointer_traits< pointer_type >::guard pg (p);
    pointer_cache_traits< pointer_type >::insert_guard ig (
      pointer_cache_traits< pointer_type >::insert (db, id, p));
    object_type& obj (pointer_traits< pointer_type >::get_ref (p));

    if (l.locked ())
    {
      init (obj, sts.image (), db);
      load_ (sts, obj);
      sts.load_delayed ();
      l.unlock ();
    }
    else
      sts.delay_load (id, obj, ig.position ());

    ig.release ();
    pg.release ();
    return p;
  }

  bool access::object_traits< ::PrintFilmTable >::
  find (database& db, const id_type& id, object_type& obj)
  {
    using namespace mysql;

    connection& conn (mysql::transaction::current ().connection ());
    object_statements< object_type >& sts (
      conn.statement_cache ().find<object_type> ());
    object_statements< object_type >::auto_lock l (sts);

    if (l.locked ())
    {
      if (!find_ (sts, id))
        return false;
    }

    reference_cache_traits< object_type >::insert_guard ig (
      reference_cache_traits< object_type >::insert (db, id, obj));

    if (l.locked ())
    {
      init (obj, sts.image (), db);
      load_ (sts, obj);
      sts.load_delayed ();
      l.unlock ();
    }
    else
      sts.delay_load (id, obj, ig.position ());

    ig.release ();
    return true;
  }

  bool access::object_traits< ::PrintFilmTable >::
  find_ (mysql::object_statements< object_type >& sts, const id_type& id)
  {
    using namespace mysql;

    id_image_type& i (sts.id_image ());
    init (i, id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    image_type& im (sts.image ());
    binding& imb (sts.out_image_binding ());

    if (im.version != sts.out_image_version () || imb.version == 0)
    {
      bind (imb.bind, im, true);
      sts.out_image_version (im.version);
      imb.version++;
    }

    select_statement& st (sts.find_statement ());
    st.execute ();
    select_statement::result r (st.fetch ());

    if (r == select_statement::truncated)
    {
      if (grow (im, sts.out_image_truncated ()))
        im.version++;

      if (im.version != sts.out_image_version ())
      {
        bind (imb.bind, im, true);
        sts.out_image_version (im.version);
        imb.version++;
        st.refetch ();
      }
    }

    st.free_result ();
    return r != select_statement::no_data;
  }

  template<>
  result< access::object_traits< ::PrintFilmTable >::object_type >
  access::object_traits< ::PrintFilmTable >::
  query< access::object_traits< ::PrintFilmTable >::object_type > (
    database& db,
    const query_type& q)
  {
    using namespace mysql;

    connection& conn (mysql::transaction::current ().connection ());

    object_statements< object_type >& sts (
      conn.statement_cache ().find<object_type> ());
    details::shared_ptr<select_statement> st;

    query_ (db, q, sts, st);

    details::shared_ptr<odb::result_impl<object_type> > r (
      new (details::shared) mysql::result_impl<object_type> (q, st, sts));
    return result<object_type> (r);
  }

  template<>
  result< const access::object_traits< ::PrintFilmTable >::object_type >
  access::object_traits< ::PrintFilmTable >::
  query< const access::object_traits< ::PrintFilmTable >::object_type > (
    database& db,
    const query_type& q)
  {
    using namespace mysql;

    connection& conn (mysql::transaction::current ().connection ());

    object_statements< object_type >& sts (
      conn.statement_cache ().find<object_type> ());
    details::shared_ptr<select_statement> st;

    query_ (db, q, sts, st);

    details::shared_ptr<odb::result_impl<const object_type> > r (
      new (details::shared) mysql::result_impl<const object_type> (q, st, sts));
    return result<const object_type> (r);
  }

  void access::object_traits< ::PrintFilmTable >::
  query_ (database&,
          const query_type& q,
          mysql::object_statements< object_type >& sts,
          details::shared_ptr<mysql::select_statement>& st)
  {
    using namespace mysql;

    image_type& im (sts.image ());
    binding& imb (sts.out_image_binding ());

    if (im.version != sts.out_image_version () || imb.version == 0)
    {
      bind (imb.bind, im, true);
      sts.out_image_version (im.version);
      imb.version++;
    }

    st.reset (new (details::shared) select_statement (
                sts.connection (),
                query_clause + q.clause (),
                q.parameters_binding (),
                imb));
    st->execute ();
  }

  void access::object_traits< ::PrintFilmTable >::
  create_schema (database& db)
  {
    ODB_POTENTIALLY_UNUSED (db);

    db.execute ("DROP TABLE IF EXISTS `PrintFilmTable`");

    db.execute ("CREATE TABLE `PrintFilmTable` ("
                "  `JobID` int not null PRIMARY KEY,"
                "  `FilmID` int not null,"
                "  `FilmAmount` int,"
                "  `Layout` varchar(32) ,"
                "  `FilmSize` varchar(16) ,"
                "  `CreateDate` date,"
                "  `CreateTime` time,"
                "  `HavePrinted` int)"
                " ENGINE=InnoDB");
  }

  static const schema_catalog_entry
  schema_catalog_entry_PrintFilmTable_ (
    "",
    &access::object_traits< ::PrintFilmTable >::create_schema);
}

// Begin epilogue.
//
//
// End epilogue.

#include <odb/post.hxx>
