//////////////////////////////////////////////////////////////////////////
/// \defgroup McsfDatabase of Common Software Business Unit
///  Copyright, (c) Shanghai United Imaging Healthcare Inc., 2011
///  All rights reserved.
///
///  \author  ZHOU qiangqiang  qiangqiang.zhou@united-imaging.com
///
///  \file       mcsf_dicomdatabase_hgfiletable.h
///  \brief   This file was generated by CodeGenerater.exe 
///              which translates database script into classes supported by ODB
///
///  \version 1.0
///  \date    11/14/2011
///  \{
//////////////////////////////////////////////////////////////////////////

#ifndef MCSF_DICOMDATABASE_HGFILETABLE_H
#define MCSF_DICOMDATABASE_HGFILETABLE_H
#include <string>
#include <odb/core.hxx>

#include <boost/date_time/gregorian/gregorian_types.hpp>// for posix_time::ptime --DATETIME
#include <boost/date_time/posix_time/posix_time_types.hpp>

#pragma db object
class HGfileTable
{
public:
    typedef boost::posix_time::ptime DATETIME_BOOST;
    typedef boost::posix_time::time_duration TIME_BOOST;
    typedef boost::gregorian::date DATE_BOOST;
HGfileTable (
const int& HG_FileID,
const int& SP_FileID,
const std::string& HG_FIlePath,
const DATE_BOOST& CreateDate,
const TIME_BOOST& CreateTime
):
m_HG_FileID(HG_FileID),
m_SP_FileID(SP_FileID),
m_HG_FIlePath(HG_FIlePath),
m_CreateDate(CreateDate),
m_CreateTime(CreateTime)
{
}

const int& GetHG_FileID () const 
{
	return m_HG_FileID;
}
void SetHG_FileID (const int& HG_FileID)
{
	m_HG_FileID = HG_FileID;
}

const int& GetSP_FileID () const 
{
	return m_SP_FileID;
}
void SetSP_FileID (const int& SP_FileID)
{
	m_SP_FileID = SP_FileID;
}

const std::string& GetHG_FIlePath () const 
{
	return m_HG_FIlePath;
}
void SetHG_FIlePath (const std::string& HG_FIlePath)
{
	m_HG_FIlePath = HG_FIlePath;
}

const DATE_BOOST& GetCreateDate () const 
{
	return m_CreateDate;
}
void SetCreateDate (const DATE_BOOST& CreateDate)
{
	m_CreateDate = CreateDate;
}

const TIME_BOOST& GetCreateTime () const 
{
	return m_CreateTime;
}
void SetCreateTime (const TIME_BOOST& CreateTime)
{
	m_CreateTime = CreateTime;
}

private:
friend class odb::access;

HGfileTable () {}

//5 parameters


#pragma db id type("int not null")
int m_HG_FileID;
//comment

#pragma db type("int")
int m_SP_FileID;
//comment

#pragma db type("varchar(256)")
std::string m_HG_FIlePath;
//comment

#pragma db type("date")
DATE_BOOST m_CreateDate;
//comment

#pragma db type("time")
TIME_BOOST m_CreateTime;
//comment
};

#endif // MCSF_DICOMDATABASE_HGFILETABLE_H
